server:
  port: 8083
fts:
  db:
    database: fts-product
    host: 47.76.158.138
    pw: 123
  swagger:
    title: 基金销售系统产品服务接口文档
    description: 基金销售系统产品服务接口文档
    package: com.github.JLQusername.controller
