server:
  port: 8084
hm:
  db:
    database: fts-query
    host: 47.76.158.138
    pw: 123
  swagger:
    title: 基金销售系统查询服务接口文档
    description: 基金销售系统查询服务接口文档
    package: com.github.JLQusername.controller
