server:
  port: 8082
hm:
  db:
    database: fts-login
    host: 47.76.158.138
    pw: 123
  swagger:
    title: 基金销售系统登录服务接口文档
    description: 基金销售系统登录服务接口文档
    package: com.github.JLQusername.controller
